version: "3"
services:
    web:
        environment:
            VIRTUAL_HOST: skychat.social,www.skychat.social
            LETSENCRYPT_HOST: skychat.social,www.skychat.social
            LETSENCRYPT_EMAIL: "badlogicgames@gmail.com"
        networks:
            - reverse_proxy
    database:
        user: 1000:1000
networks:
    reverse_proxy:
        external:
            name: nginx-proxy
