version: "3"
services:
    web:
        image: nginx:alpine
        container_name: skychat_nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../html:/www
            - ./data/logs:/logs
        links:
            - server
        networks:
            - skychat_network

    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: skychat_server
        volumes:
            - ~/firebase-service-credentials.json:/firebase-service-credentials.json
            - ./data:/data
            - ../build:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /firebase-service-credentials.json
        links:
            - database
        networks:
            - skychat_network

    database:
        image: postgres:latest
        container_name: skychat_postgres
        restart: always
        environment:
            POSTGRES_DB: skychat_db
            POSTGRES_USER: skychat
            POSTGRES_PASSWORD: ${SKYCHAT_DB_PASSWORD}
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./data/backup:/backup
        networks:
            - skychat_network

networks:
    skychat_network:
        driver: bridge
